// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reec.Inspection.SqlServer;

#nullable disable

namespace Reec.Inspection.SqlServer.Migrations
{
    [DbContext(typeof(DbContextSqlServer))]
    [Migration("20251103224836_AddLogTables")]
    partial class AddLogTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reec.Inspection.Entities.LogAudit", b =>
                {
                    b.Property<int>("IdLogAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogAudit"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime2(7)");

                    b.Property<DateOnly?>("CreateDateOnly")
                        .HasColumnType("Date");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(7)");

                    b.Property<string>("Host")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HostPort")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsHttps")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ResponseHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Scheme")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogAudit");

                    b.ToTable("LogAudit", (string)null);
                });

            modelBuilder.Entity("Reec.Inspection.Entities.LogEndpoint", b =>
                {
                    b.Property<int>("IdLogEndpoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogEndpoint"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime2(7)");

                    b.Property<DateOnly>("CreateDateOnly")
                        .HasColumnType("Date");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(7)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HostPort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Path")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("QueryString")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ResponseHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<byte>("Retry")
                        .HasColumnType("tinyint");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogEndpoint");

                    b.ToTable("LogEndpoint", (string)null);
                });

            modelBuilder.Entity("Reec.Inspection.Entities.LogHttp", b =>
                {
                    b.Property<int>("IdLogHttp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogHttp"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DateTime2(7)");

                    b.Property<DateOnly?>("CreateDateOnly")
                        .HasColumnType("Date");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(7)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Host")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HostPort")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("InnerExceptionMessage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsHttps")
                        .HasColumnType("bit");

                    b.Property<string>("MessageUser")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Scheme")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogHttp");

                    b.ToTable("LogHttp", (string)null);
                });

            modelBuilder.Entity("Reec.Inspection.Entities.LogJob", b =>
                {
                    b.Property<int>("IdLogJob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogJob"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DateTime2(7)");

                    b.Property<DateOnly?>("CreateDateOnly")
                        .IsRequired()
                        .HasColumnType("Date");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Data")
                        .HasColumnType("varchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(7)");

                    b.Property<string>("Exception")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InnerException")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("NameJob")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("StateJob")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogJob");

                    b.ToTable("LogJob", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
