// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reec.Inspection.SqlServer;

#nullable disable

namespace Reec.Inspection.SqlServer.Migrations
{
    [DbContext(typeof(DbContextSqlServer))]
    [Migration("20250109051109_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reec.Inspection.Entities.LogHttp", b =>
                {
                    b.Property<int>("IdLogHttp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogHttp"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DateTime2(7)");

                    b.Property<DateOnly?>("CreateDateOnly")
                        .HasColumnType("Date");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(7)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Host")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HostPort")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("InnerExceptionMessage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsHttps")
                        .HasColumnType("bit");

                    b.Property<string>("MessageUser")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestHeader")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Scheme")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogHttp");

                    b.ToTable("LogHttp", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
